### ISSUE TITLE
Do we even need to use Option in Rope?

### ISSUE THREAD

**Issue by hawkw** [hawkw/an-editor#16]
There's been some debate between @cjm00 and I in the past over whether it was better to use `Option<Box<Node>>` for representing empty nodes, or have a `Node::Nil` variant.

Regardless of the pros & cons of those approaches, it occurs to me now that we may not actually need _either_. Empty nodes occur very rarely. Mostly, we end up with empty nodes when we've created a brand new `Rope` with no contents, or when all the text is stored in one `Leaf` node. An empty node, then, is essentially just a `Branch` node without a `String` stored in it. Why not just represent empty nodes as `Leaf("")`? 

This would remove a lot of unnecessary boilerplate for dealing with `Option`s  which are almost always `Some`. In a majority of the cases where we need to get a value out of an `Option`, we already know that it's probably non-empty, but we have to litter our code with a lot of `if let Some(...) = self.left { ... } else { unreachable!() }` and so on. 

WDYT, @cjm00?

**Comment by deepinthebuild** [comment]
Removing the `Option`s seems correct at this point. I was originally inclined to use `Option<Box<Node>>` for performance reasons but I have no reason to think that performance will be meaningfully impacted without them, and as you said  we don't actually ever make `None` nodes. If the performance comes up at a later point we'll move to an `Arena` with indices anyway.

As to cleaning up the code, we could either make macros to reduce the boilerplate or remove the `Option`s entirely, and removing them seems like the saner choice at this point.
