### ISSUE TITLE
Consider using `clog` to generate changelogs

### ISSUE THREAD

**Issue by hawkw** [hawkw/an-editor#50]
We might want to look into using [`clog`](https://github.com/clog-tool/clog-cli), a tool for automagically generating changelogs from git history.

The one issue is that we'd have to change our commit message conventions to [the convention `clog` expects](https://github.com/conventional-changelog/conventional-changelog/blob/a5505865ff3dd710cf757f50530e73ef0ca641da/conventions/angular.md), and wouldn't be able to use it to generate changelogs from commits with our current commit message convention.

**Comment by hawkw** [comment]
I'm assigning this to everyone because I want to hear your opinions on this.

**Comment by rachlmac** [comment]
I'm on board with this change.

**Comment by twisted-pear** [comment]
I can write bad commit messages in any convention, I'm fine with this.

**Comment by hawkw** [comment]
I'd like to hear from Chris before I make this our official convention & add it to `CONTRIBUTING.md`

**Comment by hawkw** [comment]
@rachlmac might also appreciate that `clog` recommends the use of [a tool](http://commitizen.github.io/cz-cli/) to help you write commit messages.
