### ISSUE TITLE
Consider splitting rope and editor repos

### ISSUE THREAD

**Issue by hawkw** [hawkw/an-editor#59]
A lot of the tools we're using or want to be using (travis-cargo, clippy) expect each crate to have its own repo. It might make our lives easier if we changed this repo to `an-rope`, and started writing the editor core in its own repository. It would also make versioning `Rope` and the editor core independently easier, and allow us to have faster CI builds (which is always nice, especially since our CI build is getting slow already). 

Editor core could depend on Rope either as a git submodule, or just using Cargo (which would be the preferred method).

**Comment by hawkw** [comment]
Assigned everyone to this since I want to get your takes before making big changes like this.

**Comment by hawkw** [comment]
Part of why I'm bringing this up is that I'd really like to use https://clippy.bashy.io's linting service, but it won't lint crates that aren't in the repo root directory.

**Comment by twisted-pear** [comment]
already said it on the slack but i'm alright with this as long as we have an easy way to get the "right" an-rope version/commit when working on an-editor

**Comment by hawkw** [comment]
@twisted-pear: we can set up cargo to depend on tagged versions from https://crates.io, specific git hashes, or the latest commit to `master` (or any other git branch) depending  on what seems best for us.

**Comment by hawkw** [comment]
So we're all in agreement on this?

**Comment by twisted-pear** [comment]
do it!

**Comment by rachlmac** [comment]
I'm in agreement

**Comment by hawkw** [comment]
Okay, sounds good. I think I'll just make this repo the rope repo, since it already has all the rope commit history, and move it to the root directory. 

Considering making an `an-editor` github organisation that can own `an-editor/an-rope` and `an-editor/an-editor`, what do you all think?

**Comment by twisted-pear** [comment]
unless there is also the option to make a github sect or a github cabal and organisation is fine with me

**Comment by hawkw** [comment]
@twisted-pear we can call it that if you'd prefer
