### ISSUE TITLE
Replace or_zero macro with saturating_sub

### ISSUE THREAD

**Issue by hawkw** [hawkw/an-editor#78]
There are [a](https://github.com/an-cabal/an-rope/blob/0005d548856ea53e78f57295ed5ea3b89da7672b/src/internals/node.rs#L108-L109) [number](https://github.com/an-cabal/an-rope/blob/0005d548856ea53e78f57295ed5ea3b89da7672b/src/internals/node.rs#L115) [of](https://github.com/an-cabal/an-rope/blob/0005d548856ea53e78f57295ed5ea3b89da7672b/src/metric.rs#L280) [places](https://github.com/an-cabal/an-rope/blob/0005d548856ea53e78f57295ed5ea3b89da7672b/src/metric.rs#L298) where we use a macro, [`or_zero!`](https://github.com/an-cabal/an-rope/blob/b1677bba8b8dbaec007e3bdb36b42146d1ff8158/src/lib.rs#L45-L47), to subtract two unsigned numbers and return zero rather than overflowing if the result is less than zero. This is the same behaviour as the [`saturating_sub()`](https://doc.rust-lang.org/std/primitive.usize.html#method.saturating_sub) function in the standard library.

It'd be nice if instances of this macro could be replaced with `saturating_sub()`, as this is more idiomatic and might be faster on some platforms (if the CPU has a saturating subtraction operation, it could use an intrinsic...).

Once all uses of `or_zero!` are replaced, the macro definition can also be removed.

**Comment by hawkw** [comment]
This is probably pretty easy to fix, and reasonably low-priority. @rachlmac, if you want it, I'm happy to save this issue for you?

**Comment by mclark4386** [comment]
Hope I'm not stepping on toes, but I noticed it had been 13 days, so I thought I would give it a go. Please let me know if you find any issues with how I have done this code or PR! Thanks!
